### ISSUE TITLE
Is there any runtime problem of onnx in Travis CI built SINGA CPU version related to libprotobuf.so.20?

### ISSUE THREAD

**Issue by chrishkchris** [apache/singa#631]
In the log of travis CI CPU version build, it displays the error in test_onnx that cannot import libprotobuf.so.20
https://travis-ci.org/github/apache/singa/jobs/664251025#L3998
```

======================================================================
3966
ERROR: test_onnx (unittest.loader._FailedTest)
3967
----------------------------------------------------------------------
3968
ImportError: Failed to import test module: test_onnx
3969
Traceback (most recent call last):
3970
  File "/home/travis/conda-bld-1971.5/singa_1584596418932/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
3971
    module = self._get_module_from_name(name)
3972
  File "/home/travis/conda-bld-1971.5/singa_1584596418932/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
3973
    __import__(name)
3974
  File "/home/travis/conda-bld-1971.5/singa_1584596418932/test_tmp/test/python/test_onnx.py", line 24, in <module>
3975
    from singa import sonnx
3976
  File "/home/travis/conda-bld-1971.5/singa_1584596418932/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.7/site-packages/singa/sonnx.py", line 23, in <module>
3977
    import onnx.utils
3978
  File "/home/travis/conda-bld-1971.5/singa_1584596418932/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.7/site-packages/onnx/__init__.py", line 8, in <module>
3979
    from .onnx_cpp2py_export import ONNX_ML
3980
ImportError: libprotobuf.so.20: cannot open shared object file: No such file or directory
```

**Comment by chrishkchris** [comment]
maybe the version of protobuf does not match, but I am not sure

**Comment by chrishkchris** [comment]
https://blog.csdn.net/kailvechao1536/article/details/103538689 this blog says that changes to protobuf 3.9 can solve problem for onnx

**Comment by nudles** [comment]
which version of onnx are you using?

**Comment by chrishkchris** [comment]
https://github.com/apache/singa/blob/dev/tool/conda/singa/meta.yaml
currently our conda metal.yaml is using
- libprotobuf 3.6.1
- onnx >=1.3.0
maybe the two are not compatible

**Comment by nudles** [comment]
you can compare the libprotobuf of SINGA and onnx via methods here https://github.com/conda/conda/issues/2361

**Comment by chrishkchris** [comment]
OK, from the Travis CI build log the onnx version was onnx-1.6.0-py36he1b5a44_0
seems that protobuf is not specified (then should be the most latest version), so I may try to use later version.
```
dcsysh@panda8:~$ conda search onnx=1.6.0=py36he1b5a44_0 --info
Loading channels: done
onnx 1.6.0 py36he1b5a44_0
-------------------------
file name   : onnx-1.6.0-py36he1b5a44_0.tar.bz2
name        : onnx
version     : 1.6.0
build       : py36he1b5a44_0
build number: 0
size        : 2.9 MB
license     : MIT
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/onnx-1.6.0-py36he1b5a44_0.tar.bz2
md5         : 26073522c9dcaa50a8894c762668d7da
timestamp   : 2019-09-28 06:49:12 UTC
constraints :
  - python_abi * *_cp36m
dependencies:
  - libgcc-ng >=7.3.0
  - libstdcxx-ng >=7.3.0
  - numpy
  - protobuf
  - python >=3.6,<3.7.0a0
  - six
```

**Comment by chrishkchris** [comment]
Also, our singa dockerfile is using  `pip3 install protobuf`, so I may get the same version to conda

**Comment by chrishkchris** [comment]
So I will try the conda build singa onnx test case with protobuf 3.11.3 first

**Comment by nudles** [comment]
you can try. I got many troubles when I was trying to upgrade protobuf..

**Comment by joddiy** [comment]
Hi, all, please use onnx==1.5.0, we now support op set of version 10 for onnx 1.5.0. 

https://github.com/onnx/onnx/blob/master/docs/Versioning.md#released-versions

**Comment by chrishkchris** [comment]
> Hi, all, please use onnx==1.5.0, we now support op set of version 10 for onnx 1.5.0.
> https://github.com/onnx/onnx/blob/master/docs/Versioning.md#released-versions

got it, I will fix the conda version of onnx to 1.5.0. Thanks a lot

**Comment by chrishkchris** [comment]
so in the dockerfile (everyone is using for development) we may need to set to onnx==1.5.0

**Comment by chrishkchris** [comment]
After quite a exhaustive search of conda package versions' combinations, I found that this seems to be working for both onnx and singa:
```
  host:
    - swig 3.0.12
    - openblas 0.3.9
    - protobuf 3.9.2
    - glog 0.3.5
    - numpy 1.11.3
    - cudnn {{ cudnn }}       # ['cudnn' in str(build_str)]
    - dnnl {{ dnnl }}
    - python {{ python }}

  run:
    - {{ pin_compatible('glog', max_pin='x.x') }}
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - {{ pin_compatible('dnnl', max_pin='x.x') }}
    - cudnn {{ cudnn }}       # ['cudnn' in str(build_str)]
    - python {{ python }}
    - libprotobuf 3.9.2
    - libopenblas 0.3.9
    - pillow
    - future
    - tqdm
    - onnx 1.6.0
    - deprecated 1.2.7
```
onnx 1.5 fails one more test case due to numerical error, so I choose onnx 1.6

However, now there are still two errors in the test case I am investigating why:
```
+ python run.py
..............................................................................................................................EE...................................................F............................................................................................................................................................................................................................
======================================================================
ERROR: test_clip (test_onnx_backend.TestPythonOnnxBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/miniconda/conda-bld/singa_1584677090067/test_tmp/test/python/test_onnx_backend.py", line 1896, in test_clip
    name='test_clip_example')
  File "/root/miniconda/conda-bld/singa_1584677090067/test_tmp/test/python/test_onnx_backend.py", line 55, in expect
    outputs_dict = sonnx.run_node(onnx_node, input_tensors, opset_version)
  File "/root/miniconda/conda-bld/singa_1584677090067/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.6/site-packages/singa/sonnx.py", line 1300, in run_node
    return cls._run_node(onnx_node, inputs, handle, forward, opset_version)
  File "/root/miniconda/conda-bld/singa_1584677090067/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.6/site-packages/singa/sonnx.py", line 1324, in _run_node
    outputs = forward(*inputs) if handle is None else forward(
  File "/root/miniconda/conda-bld/singa_1584677090067/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.6/site-packages/singa/autograd.py", line 499, in clip
    return Clip(min, max)(x)[0]
  File "/root/miniconda/conda-bld/singa_1584677090067/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.6/site-packages/singa/autograd.py", line 245, in __call__
    return self._do_forward(*xs)
  File "/root/miniconda/conda-bld/singa_1584677090067/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.6/site-packages/singa/autograd.py", line 295, in _do_forward
    ys = self.forward(*xs)
  File "/root/miniconda/conda-bld/singa_1584677090067/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.6/site-packages/singa/autograd.py", line 479, in forward
    mask0 = singa.LTFloat(x, self.min)
TypeError: in method 'LTFloat', argument 2 of type 'float'

======================================================================
ERROR: test_clip_default (test_onnx_backend.TestPythonOnnxBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/miniconda/conda-bld/singa_1584677090067/test_tmp/test/python/test_onnx_backend.py", line 1946, in test_clip_default
    name='test_clip_default_min')
  File "/root/miniconda/conda-bld/singa_1584677090067/test_tmp/test/python/test_onnx_backend.py", line 55, in expect
    outputs_dict = sonnx.run_node(onnx_node, input_tensors, opset_version)
  File "/root/miniconda/conda-bld/singa_1584677090067/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.6/site-packages/singa/sonnx.py", line 1300, in run_node
    return cls._run_node(onnx_node, inputs, handle, forward, opset_version)
  File "/root/miniconda/conda-bld/singa_1584677090067/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.6/site-packages/singa/sonnx.py", line 1324, in _run_node
    outputs = forward(*inputs) if handle is None else forward(
TypeError: clip() missing 1 required positional argument: 'max'

======================================================================
FAIL: test_pow (test_onnx_backend.TestPythonOnnxBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/miniconda/conda-bld/singa_1584677090067/test_tmp/test/python/test_onnx_backend.py", line 1851, in test_pow
    expect(node, inputs=[x, y], outputs=[z], name='test_pow_example')
  File "/root/miniconda/conda-bld/singa_1584677090067/test_tmp/test/python/test_onnx_backend.py", line 59, in expect
    decimal=5)
  File "/root/miniconda/conda-bld/singa_1584677090067/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.6/site-packages/numpy/testing/utils.py", line 918, in assert_array_almost_equal
    precision=decimal)
  File "/root/miniconda/conda-bld/singa_1584677090067/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.6/site-packages/numpy/testing/utils.py", line 739, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 5 decimals

(mismatch 33.33333333333333%)
 x: array([   1.,   32.,  729.], dtype=float32)
 y: array([   1.     ,   32.     ,  729.00006], dtype=float32)

----------------------------------------------------------------------
Ran 400 tests in 1.563s
```

**Comment by chrishkchris** [comment]
In conclusion, I have posted an conda package versions' combinations that works for SINGA and onnx in conda environment, so I close this issue.
